# ==========================================
# ROBOT / EDGE CONFIG
# ==========================================
PROJECT_PATH: "D:\\ivs\\my_folder\\freelance\\visual_inspection\\sprint_20250908_20250912_direction\\demo_bulong\\mti_visual_inspection_ai\\1_edge_node_bk"
EDGE_IP: "10.32.11.97"
PORT: 8000
EDGE_CODE: "EDGE_001"

# =========================
# 1) CAMERA / IO
# =========================
RTSP_URL: 0  # stream RTSP (0 for laptop camera)
CAM_WIDTH: 1280
CAM_HEIGHT: 720
CAPTURE_DIR: "captures"
PRODUCT_NAME: "sp1"
FLIP_VERTICAL: false


# ==========================
# 2) MODELS (phát hiện/seg)
# ==========================
MODEL_PATH: model_checkpoint\bulong_8ly_s.pt


# ==========================
# 3) HIỂN THỊ & HÌNH HỌC
# ==========================
DISPLAY_SCALE: 1
PAD_RATIO: 0.1

# ==========================
# 4) ANOMALY (Anomalib)
# ==========================
ANOMALY_MODEL_PATH: model_checkpoint\bulong_256l.onnx
ANOMALY_DEVICE: "CPU"                 # "CPU" / "AUTO" / "GPU"
ANOMALY_INPUT_SIZE: 256
ANOMALY_SCORE_THRESHOLD: 0.7
ANOMALY_INSIDE_OVERLAP_MIN: 0.0

# vùng lỗi (tách từ anomaly map)
ANOMALY_MIN_AREA_RATIO: 0.001         # tối thiểu 0.1% diện tích crop
ANOMALY_BBOX_PAD_RATIO: 0.02          # paddingq bbox lỗi (theo crop)
SAVE_ALL_ANOMALIES: false             # lưu cả khi score < threshold nếu nằm trong vật
SHOW_ALL_ANOMALY_BOXES: true          # hiển thị bbox lỗi
ANOMALY_AMAP_THRESHOLD: 0.68          # ngưỡng heatmap
REDO_CENTER_CROP: false               # dành cho dino => true
CENTER_CROP: 448

# ==========================
# 5) DATA COLLECTOR (tool)
# ==========================
DATA_COLLECTOR_FOLDER: "data_collector"

# ==========================
# 6) DATA SYNCH
# ==========================
API_SYNC_ENABLE: false
API_SYNC_URL: "http://127.0.0.1:8030/WebApi/QualityControl/VisualInspection/SaveScannedImage"
API_TIMEOUT: 20
PRODUCTION_INSTRUCTION: "sp1"
ITEM_CODE: "sp1"
OTHER_INFO_DEFAULT: ""

# ==========================
# 7) DEFECT CLASSIFICATION
# ==========================
DEFECT_CLS_ENABLE: true
DEFECT_CLS_URL: "http://127.0.0.1:8031/search/by-image"
DEFECT_CLS_TOPK: 1
DEFECT_CLS_METRIC: "cosine"
DEFECT_CLS_SIM_THRESHOLD: 0.1

# =========================
# 8) KEYPOINTS TO DIRECTION
# =========================
KEYPOINT_DETECTION: true
KEYPOINTS_MODEL_PATH: 'model_checkpoint\bulong_8ly_keypoint_20251004.pt'
KEYPOINTS_SCORE_THRESHOLD: 0.5

# ==========================
# 9) AUTOMATIC DISK CLEANUP
# ==========================
DISK_CLEANUP_DAYS: 15.0               # số ngày lưu giữ ảnh/sessions (xoá nếu cũ hơn)
DISK_CLEANUP_INTERVAL_HOURS: 24.0     # chu kỳ tự động dọn dẹp (VD: quét mỗi 24 giờ)
