[project]
name = "vision-cli"
version = "0.1.0"
dependencies = [
    "core",
    "workflow"
]

[project.scripts]
# Định nghĩa câu lệnh `vision-cli` trỏ tới hàm `main` trong file `main.py`
vision-cli = "apps.cli.main:main"

[tool.uv.sources]
core = { workspace = true }
workflow = { workspace = true }
