# ==========================================
# MAIN SERVER CONFIG (DEFECT EMBEDDING)
# ==========================================
# FAST API CONFIG
IP: "10.32.11.97"
PORT: 8031

# DATABASE CONFIG
DATABASE_URL: "postgresql+psycopg2://postgres:12062003@localhost:5432/visual_inspection"
DEVICE: "cpu"
MODEL_NAME: "vit_small_patch14_dinov2.lvd142m"
EMBEDDING_DIM: 384
TABLE_NAME: "qc_productphotolibrary"
ENABLE_IVFFLAT_INDEX: true
IVFFLAT_LISTS: 100
IVFFLAT_DISTANCE: "cosine"
