# ==========================================
# MAIN SERVER CONFIG (DEFECT EMBEDDING)
# ==========================================
PROJECT_PATH: "C:\\Users\\IVS-1437\\Desktop\\PlatformAI\\Open-world_AI-Platform\\3_cloud_server\\defect_embedding"

# FAST API CONFIG
IP: "0.0.0.0"
PORT: 8031

# DATABASE CONFIG
DATABASE_URL: "sqlite:///./visual_inspection_server.db"
DEVICE: "cpu"
MODEL_NAME: "vit_small_patch14_dinov2.lvd142m"
EMBEDDING_DIM: 384
TABLE_NAME: "qc_productphotolibrary"
ENABLE_IVFFLAT_INDEX: false
IVFFLAT_LISTS: 100
IVFFLAT_DISTANCE: "cosine"
